language: node_js

node_js:
- 7.0.0

os:
- linux
- osx

install:
- npm install -g vsce

script:
- vsce package

# before_deploy:
# - git config --local user.name "sakiv"
# - git config --local user.email "sakiv77@outlook.com"
# - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
# - git tag $TRAVIS_TAG

deploy:
  - provider: releases
    api_key:
      secure: $GIT_TOKEN_SECURED
    file_glob: true
    file: ./*.vsix
    skip_cleanup: true
    draft: true
    overwrite: true
    on:
      repo: sakiv/web-pack
      tags: true

  # deploy to vscode extension market
  - provider: script  
    script: vsce publish -p $VSCE_TOKEN --packagePath *.vsix
    skip_cleanup: true
    on:
      tags: true
      branch: master
      # all_branches: true
      # if it's a PROD tag (something like 1.0.0), then publish extension to market.
      # condition: "$TRAVIS_OS_NAME == linux && $TRAVIS_TAG =~ $ISPRODTAG"